spring:
    datasource:
        name: test
        url: jdbc:mysql://118.190.74.13:3306/demo?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: meddkim
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


jfinal:
    modelBasePath: com.app
server:
  port: 8022
