spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: main
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.190.74.13:3306/mall?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: meddkim
    hikari:
      maximum-pool-size: 3
      leak-detection-threshold: 16000
      connection-timeout: 30000
  jackson:
    serialization:
      write_dates_as_timestamps: false
  demostr: this is a test demo

feign:
  hystrix:
    enabled: true

