spring:
  application:
    name: mall-base-message-server
  redis:
    host: 116.196.75.83
    port: 6379
    timeout: 5000
    pool:
      max-idle: 5
      min-idle: 1
      max-active: 7
      max-wait: 10000

server:
  port: 8015

redis:
  host: 116.196.75.83
  port: 6379
  timeout: 5000
  pool:
    max-idle: 5
    max-total: 50
    max-wait-millis: 10000
    min-idle: 1

