server:
  port: 8105
#  context-path: /api/product
spring:
  application:
    name: tx-manager
  redis:
    host: 116.196.75.83
    port: 6379
    timeout: 5000
    password: meddkim
    pool:
      max-idle: 5
      min-idle: 1
      max-active: 7
      max-wait: 10000
eureka:
  client:
    service-url:
      defaultZone: http://116.196.75.83:8001/eureka/
management:
  security:
    enabled: false



