server:
  port: 8102
#  context-path: /api/product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: com/mall/core/domain/mapper/**/*.xml
  type-aliases-package: com.mall.core.domain.entity
swagger:
  enabled: true
